#https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
language: node_js
node_js:
  - '8'
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

notifications:
  email: false

env:
  global:
  # do: travis encrypt GH_OAUTH_TOKEN=<githubtoken> --add
  - secure: dw8ufvNHyfG+vI4IaaKIpYMUikNb+3n3oQPp8I/pkJUhoVCj6DbvV93vtFP0OkTG/ZyZkOf7MCitC3Uj6M/octUI3jPOYF/hsC9NR2l0agDBCq/gDtHDZqksIyHEySv6TmI9TAnzUch5Fa9RMzB1U0WIlAkwDKEV5rNTDj/hLGq1UGN6HsFaIxRSXFRKbgqHoyG/OdcDBM4GgJ/qH4bJ8P8k5FvPmaH5MHNtizrPBykuZFLNzuAWuhm8eVZKua19psLPAth11V34llngVS03c8XraK9byXp3OsuHsPxmDmzcfoDLXZ2oNet++cjCXrMnb0vKARvkggU1/oZYS2VC0c5B6PJ8hHK98bJvWaCrIM+RUYF7CrwsQvaluijZKhxatuLDTSkJhVQoOpF/MLcnISY/aA9Hd//mvr4KVoqxioV8upapmjayUPJ9TZPPspk4tPpnfQZG4jtS0FUt7Jfnx4UScm+kh6T3Vd+lNZsBOJe8L/e/R71INYpnVB9yOw1UK/JsncFOT9QqFEIMh+pjYqk8qpGPfdiU2Tbs4S9FxijISNNz7aKX3Xn4vNPmhmC3+WFntyTzgAYpbpIbpeiJkbWmnqpJQ2VPod4Zu2OLTMXzCfWPqV/pznU/ycsbsFk3tONk5dLwXu3srn5TF8b6pOjSCj9jyqstmS7yGDtZ7hQ=
  - GH_USER_NAME: angegar
  - GH_PROJECT_NAME: rapport_stage_mathias
  - GIT_AUTHOR_NAME: mathias-autobuild
  - GIT_AUTHOR_EMAIL: mathias.gil51@gmail.com
  - RESULT_PDF_PATH: $TRAVIS_BUILD_DIR/thesis.pdf
  - TZ: "Europe/Zurich"
  
cache:
  directories:
    - node_modules
# allow headful tests
before_install:
  - chmod u+x ./scripts/md2pdf.sh
  - chmod u+x ./scripts/publish.sh
  # Install markdown to pdf
  - "npm i -g md-to-pdf"
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
script: "./scripts/md2pdf.sh"

after_success:
- "./scripts/publish.sh"

deploy:
    provider: releases
    api_key: $GH_OAUTH_TOKEN
    file_glob: true
    file: ./*.pdf
    overwrite: true
    skip_cleanup: true
    draft: true
